
const VISUAL_MODE = {
  EMPTY: "EMPTY",
  SHOW: "SHOW",
  FORM: {
    CREATE: "CREATE",
    EDIT: "EDIT"
  },
  STATUS: {
    SAVING: "SAVING",
    DELETING: "DELETING"
  },
  CONFIRM: "CONFIRM",
  ERROR_SAVE: "ERROR_SAVE",
  ERROR_DELETE: "ERROR_DELETE"
};

export default VISUAL_MODE;