
const VISUAL_MODE = {
  EMPTY: "EMPTY",
  SHOW: "SHOW",
  FORM: {
    CREATE: "CREATE",
    EDIT: "EDIT"
  },
  STATUS: {
    SAVING: "SAVING",
    DELETING: "DELETING"
  },
  CONFIRM: "CONFIRM",
  ERROR_SAVE: "ERROR_SAVE",
  ERROR_DELETE: "ERROR_DELETE",
  ERROR_NAME_EMPTY: "ERROR_NAME_EMPTY",
  ERROR_INTERVIEWER_NOT_SELECTED: "ERROR_INTERVIEWER_NOT_SELECTED"
};

export default VISUAL_MODE;